### PR TITLE
Add rich text support

### PR DESCRIPTION
**Pull request by datapharmer**
Adds support for rich text in datatable instead of only plain text.

### CODE REVIEW

**Comment by ericrsmith35** [comment]
@datapharmer Can you point me to an org where you have this implemented.  I think this is going to be a nice addition and possible a good template for adding other custom column types.

**Comment by datapharmer** [comment]
Here is an example from a current project:

formula field generates url with pretty name:

Capture2

and rich text properly renders it:

Capture


I hope that helps!

**Comment by ericrsmith35** [comment]
Thank you.  Besides Formulas using HYPERLINK or IMAGE, can you think of
some other use cases?  Is there a way to generate HTML formatted values in
a formula field?

Eric

**Comment by datapharmer** [comment]
Yes you can embed some html thisnway. In addition to formulas you can use
an actual richtext type field to display formatted text and data as
supported by the editor where converting to text would show the escaped
data.

**Comment by ericrsmith35** [comment]
I've incorporated your updates into the current version of my code for
testing.  I need to get it posted  online.  I did find another great use
case by putting the IMAGE function inside of the HYPERLINK function in a
formula field.

Eric

**Comment by ericrsmith35** [comment]
Included in PR#30.

**Pull request closed without merging**
